<?php

namespace Siwapp\RecurringInvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecurringInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecurringInvoiceRepository extends EntityRepository
{
}