<?php

namespace Siwapp\InvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Siwapp\CoreBundle\Repository\AbstractInvoiceRepository;

use Siwapp\InvoiceBundle\Entity\Invoice;


/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends AbstractInvoiceRepository
{
    /** 
     * getNextNumber
     * Obtain the next numer available for the provided series
     * @param \Siwapp\CoreBundle\Entity\Serie @serie
     * @return integer
     */
    public function getNextNumber($serie)
    {
        $em = $this->getEntityManager();
        $number = $em->createQuery('SELECT MAX(i.number)  
            FROM \Siwapp\InvoiceBundle\Entity\Invoice i  JOIN i.serie s
            WHERE i.status!=:draft AND i.serie=:serie')
            ->setParameters(array(
                                  'draft'=>Invoice::DRAFT, 
                                  'serie'=>$serie))
            ->getSingleScalarResult();

        return $number ? intval($number) + 1: $serie->getFirstNumber();
        
    }
}